from typing import AsyncIterator, Protocol


class LLM(Protocol):
    def generate(self, prompt: str, system_prompt: str | None = None) -> str: ...

    def stream(self, prompt: str, system_prompt: str | None = None) -> AsyncIterator[str]: ...

    def count_tokens(self, text: str) -> int: ...
