import { useState, useRef, useEffect, KeyboardEvent } from 'react'
import { Button } from '@/components/ui/button'
import { Send, Loader2 } from 'lucide-react'

interface ChatInputProps {
  onSend: (message: string) => void
  disabled: boolean
  streaming: boolean
}

export function ChatInput({ onSend, disabled, streaming }: ChatInputProps) {
  const [text, setText] = useState('')
  const textareaRef = useRef<HTMLTextAreaElement>(null)

  useEffect(() => {
    if (textareaRef.current) {
      textareaRef.current.style.height = 'auto'
      textareaRef.current.style.height = `${Math.min(textareaRef.current.scrollHeight, 150)}px`
    }
  }, [text])

  const handleSend = () => {
    if (!text.trim() || disabled || streaming) return
    onSend(text.trim())
    setText('')
    if (textareaRef.current) {
      textareaRef.current.style.height = 'auto'
    }
  }

  const handleKeyDown = (e: KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      handleSend()
    }
  }

  return (
    <div className="border-t bg-card px-4 py-3">
      <div className="max-w-3xl mx-auto flex items-end gap-2 bg-background border rounded-2xl px-3 py-2 focus-within:border-primary focus-within:ring-2 focus-within:ring-primary/20 transition-all">
        <textarea
          ref={textareaRef}
          value={text}
          onChange={(e) => setText(e.target.value)}
          onKeyDown={handleKeyDown}
          placeholder="Ask a question about GigaCorp..."
          rows={1}
          className="flex-1 bg-transparent border-none outline-none resize-none text-sm leading-relaxed max-h-[150px] min-h-[24px] placeholder:text-muted-foreground"
          disabled={disabled}
        />
        <Button
          size="icon"
          onClick={handleSend}
          disabled={!text.trim() || disabled || streaming}
          className="shrink-0 rounded-full h-9 w-9"
        >
          {streaming ? (
            <Loader2 className="h-4 w-4 animate-spin" />
          ) : (
            <Send className="h-4 w-4" />
          )}
        </Button>
      </div>
      <p className="text-center text-[11px] text-muted-foreground mt-2">
        Responses are generated by AI based on GigaCorp's knowledge base. Verify critical information.
      </p>
    </div>
  )
}
